---

- name: upload traffic profile
  template:
    src: '{{profile}}_profile.py'
    dest: '{{ trex_install_dir }}/{{profile}}_profile.py'

- name: GET dpdk-rss-flows.py file
  get_url:
    url: "https://git.dpdk.org/dpdk/plain/usertools/dpdk-rss-flows.py"
    dest: "{{ trex_install_dir }}/rss.py"
    mode: 0755
  when: profile == 'imbalance'

- set_fact:
      profile_tunable: --prof-tun=queue-ratios={{ queue_ratios }}
  when: profile == 'imbalance'

- name: 'binary search: datapath={{datapath}} {{profile}}'
  command:
    cmd: >
      ./ndr --stl -v --ports 0 1 -t {{it_interval}} -ft {{first_it_time}} --force-map --bi-dir --opt-bin-search
        --profile {{profile}}_profile.py {{ profile_tunable }} -o {{output_file}}
    chdir: '{{ trex_install_dir }}/'
  register: ndr_out
  tags: test

- debug:
    msg: '{{ndr_out.stdout_lines}}'
  tags: test

- slurp:
    src: '{{output_file}}'
  register: results
  tags: test

- set_fact:
    stats: '{{results.content | b64decode | from_json}}'
  tags: test

- set_fact:
    rx_bps: '{{stats.results.rx_bps | default(0)}}'
    rx_pps: '{{stats.results.rx_pps | default(0)}}'
  tags: test

- debug:
    msg: 'best iteration: {{rx_bps | human}} bit/s ({{rx_pps | human}} pkts/s)'
  tags: test

- name: 'expected rate: {{expected_pps | human}} pkts/s'
  assert:
    that: 'rx_pps|float > expected_pps|float'
  tags: test
