---

- name: install runtime dependencies
  dnf:
    name:
      - python3
    state: installed
  tags: install

- name: stop existing trex server
  command: pkill -x _t-rex-64
  ignore_errors: true
  tags: setup

- name: Create TRex install directory
  file:
    path: "{{ trex_install_dir }}"
    state: directory
    mode: "0755"
  tags: install

- name: Download and Extract TRex release
  unarchive:
    src: "{{ trex_release_url }}/{{ trex_version }}.tar.gz"
    dest: "{{ trex_install_dir }}"
    remote_src: yes
    extra_opts: --strip-components=1
    validate_certs: no
  tags: install

- name: upload trex configuration
  copy:
    dest: /etc/trex_cfg.yaml
    content: '{{trex_config | to_nice_yaml}}'
  tags: setup

- name: start trex server
  shell:
    cmd: 'nohup ./t-rex-64 --cfg /etc/trex_cfg.yaml -i </dev/null >/tmp/trex.log 2>&1 &'
    chdir: '{{ trex_install_dir }}/'
  tags: setup

- name: wait for trex server
  wait_for:
    port: 4500
    delay: 5
    timeout: 30
  tags: setup
